add unit tests for the enumerables
Bluette1/enumerables pull request #4
Opened 2020-06-04 08:31 UTC by Bluette1

2020-06-04 23:19 UTC, Forison requested changes
## Status:: Changes required❌
# 🙋‍♂️ Team!!!
#### You have done a great on this one, I am impressed at the level of your test, however there some behaviors which are inconsistent with the original Ruby method.
#### my_each test
* [ ] This test is failing ```expect(item.my_each{|x| x}).to eql(item.each{|x| x})``` check the expectation in the image below
![EX1](https://user-images.githubusercontent.com/29695661/83817655-51bd8680-a693-11ea-8773-c9f58188f9aa.png)
you could verify it from the behavior of the method
```p [1, 2, 3, 4].each{|x| x}``` should return same results as  ```p [1, 2, 3, 4].my_each{|x| x}```

#### my_each_with_index test
* [ ] This test is failing ```expect(item.my_each_with_index{|x| x}).to eql(item.each{|x| x})``` check the expectation in the image below
![ex2](https://user-images.githubusercontent.com/29695661/83817947-08ba0200-a694-11ea-9299-a2d67be35a61.png)
you could verify it from the behavior of the method
```p [1, 2, 3, 4].each_with_index{|x| x}``` should return same results as 
```p [1, 2, 3, 4].my_each_with_index{|x| x}```
* [ ]  I will point out a few things below👇 that you should do to refactor your tests to save space as well as observing the DRY rule of Ruby🤗.
* [ ] Add a "Getting started" to the readme, in that section describe how to set up the project on a local machine. This should come to complement the part when you indicated  run```rspec```.

**[OPTIONAL]**
Add a description to the repository, it makes your repository more professional. You will also be asked to do this when you are about to graduate.

## That is it, kindly make the change and submit a re-review🤠 .
#### Happy coding🤖.
Addo Forison

2020-06-04 23:19 UTC, Forison commented on spec/enumerable_spec.rb
> +    let(:item) { [1, 2, 3, 4] }
- Kindly move this ```let(:item) { [1, 2, 3, 4] }``` line and place it between lines 3 and 4 thus making it a global variable. Then, remove it from all other places they currently exist.

2020-06-04 23:19 UTC, Forison commented on spec/enumerable_spec.rb
> +    let(:item) { %w[ant bear cat] }
- Kindly move this ```let(:item) { %w[ant bear cat] }``` line and place it between lines 3 and 4 thus making it a global variable. Then, remove it from all other places they currently exist.

2020-06-04 23:19 UTC, Forison commented on spec/enumerable_spec.rb
> +    let(:contexts) { [[[1, 2i, 3.14], %w[ant bear cat], [nil, true, 99]], [Numeric, String, Integer]] }
Do same for ```let(:contexts) { [[[1, 2i, 3.14], %w[ant bear cat], [nil, true, 99]], [Numeric, String, Integer]] } ```

2020-06-05 10:34 UTC, Bluette1 commented
@Forison Thank you very much for your feedback!

2020-06-05 23:23 UTC, rOluochKe approved these changes
Hello Team!
### You have done great and for also making changes from the previous review :clap: The test passes and the project has been approved. Congratulations :boom: :100:
### You can merge and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

2020-06-06 06:05 UTC, Bluette1 commented
@rOluochKe Thank you very much  for your review and feedback!

2020-06-06 06:05 UTC, merged